<?php

/**
 * Implements hook_menu().
 */
function ophal_export_menu() {
  $items['ophal_export'] = array(
    'page callback' => 'ophal_export_router',
    'access callback' => TRUE,
  );
  return $items;
}

function ophal_export_router($action, $class, $id = NULL) {
  global $db_type;

  $request_body = file_get_contents('php://input');

  $values = json_decode($request_body);

  if ($values->token != 'YOUR TOKEN HERE') {
    header('403 Forbidden');
    die();
  }

  header('content-type: application/json; charset=utf-8');

  if ($action == 'count') {
    if ($class == 'node') {
      $res = db_query('SELECT COUNT(*) total FROM {node};');
      $count = db_fetch_object($res);
      $total = $count->total;
    }
    elseif ($class == 'comment') {
      $res = db_query('SELECT COUNT(*) total FROM {comments};');
      $count = db_fetch_object($res);
      $total = $count->total;
    }
    elseif ($class == 'user') {
      $res = db_query('SELECT COUNT(*) total FROM {users};');
      $count = db_fetch_object($res);
      $total = $count->total - 1; // user  "anonymous" is not exported
    }
    elseif ($class == 'alias') {
      $res = db_query("SELECT COUNT(*) total FROM {url_alias} WHERE src like 'node/%';");
      $count = db_fetch_object($res);
      $total = $count->total;
    }
    $object = (object)array('total' => $total);
  }
  elseif ($action == 'list') {
    if ($db_type == 'mysql' or $db_type == 'mysqli') {
      $group_field = 'GROUP_CONCAT(id)';
      $limit = 'LIMIT 0, 100';
    }
    elseif ($db_type == 'pgsql') {
      $group_field = "array_to_string(array_agg(id), ',')";
      $limit = 'LIMIT 100 OFFSET 0';
    }

    if ($class == 'node') {
      $res = db_query('SELECT ' . $group_field . ' list FROM (SELECT nid id FROM {node} WHERE nid > %d ORDER BY nid ' . $limit . ') list', $id);
      $list = db_fetch_object($res);
      $object = explode(',', $list->list);
    }
    elseif ($class == 'comment') {
      $res = db_query('SELECT ' . $group_field . ' list FROM (SELECT cid id FROM {comments} WHERE cid > %d ORDER BY cid ' . $limit . ') list', $id);
      $list = db_fetch_object($res);
      $object = explode(',', $list->list);
    }
    elseif ($class == 'user') {
      $res = db_query('SELECT ' . $group_field . ' list FROM (SELECT uid id FROM {users} WHERE uid > %d ORDER BY uid ' . $limit . ') list', $id);
      $list = db_fetch_object($res);
      $object = explode(',', $list->list);
    }
    elseif ($class == 'alias') {
      $res = db_query('SELECT ' . $group_field . " list FROM (SELECT pid id FROM {url_alias} WHERE pid > %d ORDER BY pid " . $limit . ') list', $id);
      $list = db_fetch_object($res);
      $object = explode(',', $list->list);
    }
  }
  elseif($action == 'fetch') {
    switch ($class) {
      case 'user':
        $object = user_load($id);
        break;
      case 'node':
        $object = node_load($id);
        break;
      case 'comment':
        $res = db_query('SELECT * FROM {comments} WHERE cid = %d', $id);
        $object = db_fetch_object($res);
        break;
      case 'alias':
        $res = db_query('SELECT * FROM {url_alias} WHERE pid = %d', $id);
        $object = db_fetch_object($res);
        break;
    }
  }

  print json_encode($object);

  exit();
}

